openapi: 3.0.0

info:
  title: blog api
  version: '1.0'
servers:
  - url: 'https://ru.usatukirill96.com/api'
    description: Production

tags:
  - name: distance

paths:
  /posts:
    get:
      summary: Get all posts for the main page
      tags:
        - posts
      parameters:
        - in: query
          name: shift
          description: The last post id.
          required: false
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: Main page response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "My first post ever"
                    created:
                      type: string
                      pattern: RFC(3339)
                      example: "2022-09-29T18:22:10Z"
                    image:
                      type: string
                      example: "https://ru.usatukirill96.com/uploads/upload-472703852.png"
  /post/(int:post_id)/:
    get:
      summary: Get a single post info
      tags:
        - post
      parameters:
        - in: query
          name: post_id
          description: Post id.
          required: true
          schema:
            type: integer
            example: 1

      responses:
        '200':
          description: Single page response
          content:
            application/json:
              schema:
                properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "My first post ever"
                    text:
                      type: string
                      example: "Text of the post"
                    created:
                      type: string
                      pattern: RFC(3339)
                      example: "2022-09-29T18:22:10Z"
                    image:
                      type: string
                      example: "https://ru.usatukirill96.com/uploads/upload-472703852.png"

        '404':
          description: Post not found
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: string
                    example: "Post not found"
